### ISSUE TITLE
Error on submitted-tx-hash-tracker example plugin

### ISSUE THREAD

**Issue by okwme** [MetaMask/snaps-cli#55]
```
cd examples/submitted-tx-hash-tracker
snap serve
```
open http://localhost:8083  
click connect  
approve two metamask requests  
click "Log TX Hashes"  
get:  
```
Problem happened: Plugin RPC message handler not found.
```

**Comment by rekmarks** [comment]
This example snap will soon be deleted. In the future it will be replaced with a different version.

I will now close this issue.
